version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    networks:
      - kong-net

  kong-migrations:
    image: kong:3.5.0
    command: kong migrations bootstrap
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database
    networks:
      - kong-net

  kong:
    image: kong:3.5.0
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"   # Kong Proxy
      - "8001:8001"   # Kong Admin API
    depends_on:
      - kong-database
      - kong-migrations
    networks:
      - kong-net

  # wms-backend:
  #   image: kennethreitz/httpbin
  #   container_name: wms-backend
  #   ports:
  #     - "9001:80"
  #   networks:
  #     - kong-net

  # sofia-backend:
  #   image: kennethreitz/httpbin
  #   container_name: sofia-backend
  #   ports:
  #     - "9002:80"
  #   networks:
  #     - kong-net

  # md-backend:
  #   image: kennethreitz/httpbin
  #   container_name: md-backend
  #   ports:
  #     - "9003:80"
  #   networks:
  #     - kong-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - kong-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - kong-net

networks:
  kong-net:
    driver: bridge 