version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5434:5432"
    networks:
      - kong-net
    restart: unless-stopped

  kong-migrations:
    image: kong:3.5.0
    command: sh -c "kong migrations bootstrap && kong migrations up && kong migrations finish"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database
    networks:
      - kong-net
    restart: "no"

  kong:
    image: kong:3.5.0
    container_name: kong
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - kong-database
      - kong-migrations
    networks:
      - kong-net
    restart: unless-stopped

  backend-md:
    build: ./backend-md
    container_name: backend-md
    env_file:
      - ./backend-md/.env.docker
    ports:
      - "9001:9001"
    networks:
      - kong-net
    restart: unless-stopped

  backend-ryo:
    build: ./backend-ryo
    container_name: backend-ryo
    env_file:
      - ./backend-ryo/.env
    ports:
      - "9002:9002"
    networks:
      - kong-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # Mount static files untuk nginx
      - /opt/backend-ryo/staticfiles:/app/staticfiles
      - /opt/backend-ryo/media:/app/media
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=https://api.kcsi.id/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - "3000:3000"
    networks:
      - kong-net
    volumes:
     - grafana-data:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - kong-net
    restart: unless-stopped

volumes:
  grafana-data:
  prometheus-data:

networks:
  kong-net:
    driver: bridge
