version: '3.8'

services:
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5434:5432"
    networks:
      - kong-net
    restart: unless-stopped

  kong-migrations:
    image: kong:3.5.0
    command: sh -c "kong migrations bootstrap && kong migrations up && kong migrations finish"
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    depends_on:
      - kong-database
    networks:
      - kong-net
    restart: "no"

  kong:
    image: kong:3.5.0
    container_name: kong
    environment:
      KONG_DATABASE: 'off'
      KONG_DECLARATIVE_CONFIG: /kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    volumes:
      - ./kong.yml:/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - kong-database
      - kong-migrations
    networks:
      - kong-net
    restart: unless-stopped

  backend-md:
    build: ./backend-md
    container_name: backend-md
    env_file:
      - ./backend-md/.env.docker
    ports:
      - "9001:9001"
    networks:
      - kong-net
    restart: unless-stopped

  backend-ryo:
    build: ./backend-ryo
    container_name: backend-ryo
    env_file:
      - ./backend-ryo/.env
    volumes:
      - ./backend/media:/app/media
      # - static_volume:/app/staticfiles  # Mount static files volume
      - ./staticfiles:/app/staticfiles  # Mount for WSL Nginx access
    ports:
      - "9002:9002"
    networks:
      - kong-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  service-meta:
    build:
      context: ./service-meta
      dockerfile: Dockerfile  # Use production Dockerfile, not Dockerfile.dev
    container_name: service-meta
    env_file:
      - ./service-meta/.env  # Use production env file
    ports:
      - "9003:9003"
    environment:
      - NODE_ENV=production  # Production environment
      - ORA_SDTZ=UTC
      # Oracle Instant Client paths (match Dockerfile)
      - LD_LIBRARY_PATH=/opt/oracle/instantclient
      - ORACLE_HOME=/opt/oracle/instantclient
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "metauatdb.nna.net:host-gateway"
    restart: unless-stopped
    # Production optimizations
    deploy:
      resources:
        limits:
          memory: 1GB
          cpus: '0.5'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9003/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SERVER_ROOT_URL=http://api.kcsi.id/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SERVER_HTTP_PORT=3000
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_SECURITY_ALLOW_EMBEDDING=true
    ports:
      - "3000:3000"
    networks:
      - kong-net
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - kong-net
    restart: unless-stopped

volumes:
  grafana-data:

networks:
  kong-net:
    driver: bridge