global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kong'
    metrics_path: /metrics
    static_configs:
      - targets: ['kong:8001'] 
  - job_name: 'wms-backend-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['wms-backend:80']
  - job_name: 'sofia-backend-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['sofia-backend:80']
  - job_name: 'md-backend-api'