global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kong'
    metrics_path: /metrics
    static_configs:
      - targets: ['kong:8001']
  - job_name: 'backend-md'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-md:9001']
  - job_name: 'backend-ryo'
    metrics_path: /metrics
    static_configs:
      - targets: ['backend-ryo:9002']
  - job_name: 'service-meta'
    metrics_path: /metrics
    static_configs:
      - targets: ['service-meta:9003']
